name: Test

on:
  workflow_dispatch:
    inputs:
      deploy-to-test:
        description: "Deploy to test?"
        type: boolean
        default: true
      environment-name:
        description: "Environment Name"
        type: string

jobs:
  echo-value:
    name: Echo Value
    environment: ${{ inputs.environment-name }}
    runs-on: ubuntu-latest
    steps:
      - name: Value
        run: |
          echo "${{ inputs.deploy-to-test }}"
          echo "${{ github.event_name }}"
          echo "${{ secrets.SECRET_VALUE }}"
  run-check:
    name: Run Check
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || inputs.deploy-to-test
    steps:
      - name: Run
        run: |
          echo "Ran the job"